
server:
  port: 7071
#  ssl:
#    key-alias: intallyshwisdom
#    key-store: classpath:iw.jks
#    key-store-type: JKS
#    key-password: iw@12345



spring:
    servlet:
      multipart:
        enabled: true
        max-file-size: 5MB
        max-request-size: 5MB
          


    datasource:
        url: jdbc:mysql://localhost:3306/intallyshwisdom?createDatabaseIfNotExist=true
#        url: jdbc:mysql://192.168.2.47:3306/test
        username: amit
        password: 12345
        driver-class-name: com.mysql.cj.jdbc.Driver

     
    mail:
        host: smtp.gmail.com
        password: uxmobsapevveephk
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: chandunawapara@gmail.com       
        
        
    jpa: 
        properties:
            hibernate:
#                format_sql: true
        hibernate:
            ddl-auto: update

        show-sql: true
    jackson:
      time-zone: IST  

logging:
   file:
    name: "C:/logs/intallysh-wisdom-service-error.log"
   logback:
    rollingpolicy:
      file-name-pattern: C:/logs/intallysh-wisdom-service-%d{yyyy-MM-dd}.%i.log

files:
  storage: J:/iw-accounting-app/accounting-data-main/

   